import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton, useAuth } from '@clerk/clerk-react'
import { createRoot } from 'react-dom/client'
import { useEffect, useMemo, useState } from 'react'
import './styles.css'

type Match = { id: string; homeTeamName: string; awayTeamName: string; competitionName: string; matchDate: string; status: string; homeScore: number | null; awayScore: number | null; isFinished: boolean }
type Leader = { name: string; played: number; exact: number; correct: number; points: number }
const publicKey = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY

function api<T>(path: string, token: () => Promise<string | null>, init?: RequestInit) { return token().then(t => fetch(`/api/${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(t ? { Authorization: `Bearer ${t}` } : {}), ...init?.headers } }).then(async r => { if (!r.ok) throw new Error((await r.json() as { error?: string }).error ?? 'İstek başarısız'); return r.json() as Promise<T> })) }
function Countdown({ date }: { date: string }) { const [now, setNow] = useState(Date.now()); useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id) }, []); const s = Math.max(0, Math.floor((new Date(date).getTime() - now) / 1000)); return <span>{Math.floor(s / 86400)} gün {String(Math.floor(s % 86400 / 3600)).padStart(2,'0')}:{String(Math.floor(s % 3600 / 60)).padStart(2,'0')}:{String(s % 60).padStart(2,'0')}</span> }
function App() { const { getToken } = useAuth(); const [matches, setMatches] = useState<Match[]>([]); const [leaders, setLeaders] = useState<Leader[]>([]); const [error, setError] = useState(''); const [scores, setScores] = useState({ home: 2, away: 1 }); const [message, setMessage] = useState(''); const [tab, setTab] = useState<'home'|'matches'|'leaderboard'>('home');
  const load = () => Promise.all([api<Match[]>('matches', getToken), api<Leader[]>('leaderboard', getToken)]).then(([m,l]) => { setMatches(m); setLeaders(l) }).catch(e => setError(e instanceof Error ? e.message : 'Veriler yüklenemedi.'))
  useEffect(() => { void load() }, [])
  const next = useMemo(() => matches.find(m => m.status === 'scheduled' && new Date(m.matchDate) > new Date()), [matches]);
  const save = async () => { if (!next) return; setMessage(''); try { await api(`matches/${next.id}/prediction`, getToken, { method: 'PUT', body: JSON.stringify({ homeScore: scores.home, awayScore: scores.away }) }); setMessage('Tahminin kaydedildi. Bol şans!') } catch (e) { setMessage(e instanceof Error ? e.message : 'Tahmin kaydedilemedi.') } }
  return <main><header><div className="brand"><i>G</i><span>GALA<span>TAHMİN</span></span></div><nav>{(['home','matches','leaderboard'] as const).map(x => <button className={tab===x?'active':''} onClick={() => setTab(x)} key={x}>{x === 'home' ? 'Ana Sayfa' : x === 'matches' ? 'Maçlar' : 'Liderlik'}</button>)}</nav><SignedIn><UserButton /></SignedIn><SignedOut><SignInButton><button className="signin">Giriş yap</button></SignInButton></SignedOut></header>
    {error && <p className="error">{error}</p>}
    {tab === 'home' && <section className="hero">{next ? <><p className="eyebrow">SIRADAKİ RESMİ MAÇ</p><div className="fixture"><strong>{next.homeTeamName}</strong><span className="vs">vs</span><strong>{next.awayTeamName}</strong></div><p>{new Intl.DateTimeFormat('tr-TR', { dateStyle: 'long', timeStyle: 'short', timeZone: 'Europe/Istanbul' }).format(new Date(next.matchDate))} · {next.competitionName}</p><div className="countdown"><small>TAHMİNLERİN KAPANMASINA</small><Countdown date={next.matchDate} /></div><div className="predict"><label>{next.homeTeamName}<input type="number" min="0" max="20" value={scores.home} onChange={e => setScores(s => ({...s, home: Number(e.target.value)}))}/></label><b>—</b><label>{next.awayTeamName}<input type="number" min="0" max="20" value={scores.away} onChange={e => setScores(s => ({...s, away: Number(e.target.value)}))}/></label></div><button className="save" onClick={() => void save()}>Tahminimi Kaydet</button>{message && <p className="message">{message}</p>}</> : <><p className="eyebrow">GALATASARAY</p><h1>Yeni bir maç bekleniyor.</h1><p>Fikstür güncellendiğinde burada görünecek.</p></>}</section>}
    {tab === 'matches' && <section><h1>Maçlar</h1><div className="cards">{matches.map(m => <article className="card" key={m.id}><small>{m.competitionName}</small><h3>{m.homeTeamName} <em>{m.homeScore ?? '–'} : {m.awayScore ?? '–'}</em> {m.awayTeamName}</h3><p>{new Intl.DateTimeFormat('tr-TR', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Europe/Istanbul' }).format(new Date(m.matchDate))}</p><span className={'badge '+m.status}>{m.status}</span></article>)}{!matches.length && <p>Henüz gösterilecek maç yok.</p>}</div></section>}
    {tab === 'leaderboard' && <section><h1>Sezon Liderliği</h1><div className="table"><div className="row head"><span>#</span><span>Oyuncu</span><span>Maç</span><span>Tam skor</span><span>Puan</span></div>{leaders.map((l, i) => <div className="row" key={l.name}><span>{i+1}</span><strong>{l.name}</strong><span>{l.played}</span><span>{l.exact}</span><b>{l.points}</b></div>)}{!leaders.length && <p>İlk tamamlanan maçtan sonra puanlar burada oluşacak.</p>}</div></section>}
  </main> }

createRoot(document.getElementById('root')!).render(publicKey ? <ClerkProvider publishableKey={publicKey}><App /></ClerkProvider> : <div className="setup">Başlamak için <code>VITE_CLERK_PUBLISHABLE_KEY</code> değerini <code>.env</code> dosyasına ekleyin.</div>)
