import { eq, and, asc, desc } from 'drizzle-orm'
import { db, sql } from '../src/db'
import { matches, predictions, users } from '../src/db/schema'
import { calculatePredictionPoints } from '../src/lib/scoring'
import { ApiError, requireAdmin, requireUser } from '../src/server/auth'
import { syncGalatasarayFixtures } from '../src/server/fixtures'

type Req = { method?: string; url?: string; headers: Record<string, string | string[] | undefined>; body?: unknown }
type Res = { status: (n: number) => Res; json: (v: unknown) => void; setHeader: (n: string, v: string) => void }
const body = (r: Req) => typeof r.body === 'string' ? JSON.parse(r.body) as unknown : r.body
const replyError = (res: Res, error: unknown) => { const e = error instanceof ApiError ? error : new ApiError(500, 'Sunucu hatası.'); if (!(error instanceof ApiError)) console.error(error); res.status(e.status).json({ error: e.message }) }
const allowedScore = (n: unknown) => typeof n === 'number' && Number.isInteger(n) && n >= 0 && n <= 20

export default async function handler(req: Req, res: Res) { try { const path = new URL(req.url ?? '/', 'http://local').pathname.replace(/^\/api\/?/, '').split('/').filter(Boolean); res.setHeader('Cache-Control', 'no-store');
  if (path[0] === 'cron' && path[1] === 'sync-fixtures') { if (req.headers.authorization !== `Bearer ${process.env.CRON_SECRET}`) throw new ApiError(401, 'Geçersiz cron anahtarı.'); res.status(200).json({ synced: await syncGalatasarayFixtures() }); return }
  if (path[0] === 'matches' && path.length === 1 && req.method === 'GET') { res.status(200).json(await db.select().from(matches).where(eq(matches.isActive, true)).orderBy(asc(matches.matchDate))); return }
  if (path[0] === 'matches' && path.length === 2 && req.method === 'GET') { const [match] = await db.select().from(matches).where(eq(matches.id, path[1])).limit(1); if (!match) throw new ApiError(404, 'Maç bulunamadı.'); res.status(200).json(match); return }
  if (path[0] === 'matches' && path[2] === 'prediction' && ['POST','PUT'].includes(req.method ?? '')) { const user = await requireUser(req); const input = body(req) as { homeScore?: unknown; awayScore?: unknown }; if (!allowedScore(input?.homeScore) || !allowedScore(input?.awayScore)) throw new ApiError(400, 'Skorlar 0-20 arasında tam sayı olmalı.'); const result = await sql.query('INSERT INTO predictions (match_id, user_id, predicted_home_score, predicted_away_score, updated_at) SELECT $1, $2, $3, $4, now() FROM matches WHERE id = $1 AND status <> \'postponed\' AND match_date > now() ON CONFLICT (match_id, user_id) DO UPDATE SET predicted_home_score = EXCLUDED.predicted_home_score, predicted_away_score = EXCLUDED.predicted_away_score, updated_at = now() RETURNING *', [path[1], user.id, input.homeScore, input.awayScore]); if (!result.length) throw new ApiError(409, 'Tahminler bu maç için kilitlendi.'); res.status(200).json(result[0]); return }
  if (path[0] === 'matches' && path[2] === 'predictions' && req.method === 'GET') { const user = await requireUser(req); const [match] = await db.select().from(matches).where(eq(matches.id, path[1])).limit(1); if (!match) throw new ApiError(404, 'Maç bulunamadı.'); const locked = match.status !== 'postponed' && match.matchDate <= new Date(); const rows = await db.select({ prediction: predictions, user: users }).from(predictions).innerJoin(users, eq(predictions.userId, users.id)).where(locked ? eq(predictions.matchId, match.id) : and(eq(predictions.matchId, match.id), eq(predictions.userId, user.id))); res.status(200).json(rows.map(({ prediction, user: player }) => ({ ...prediction, displayName: player.displayName, points: match.isFinished && match.homeScore !== null && match.awayScore !== null ? calculatePredictionPoints({ home: match.homeScore, away: match.awayScore }, { home: prediction.predictedHomeScore, away: prediction.predictedAwayScore }) : null }))); return }
  if (path[0] === 'leaderboard' && req.method === 'GET') { const rows = await db.select({ user: users, prediction: predictions, match: matches }).from(predictions).innerJoin(users, eq(predictions.userId, users.id)).innerJoin(matches, eq(predictions.matchId, matches.id)).where(and(eq(matches.isFinished, true), eq(matches.isActive, true))); const table = new Map<string, { name: string; played: number; exact: number; correct: number; points: number }>(); for (const r of rows) { if (r.match.homeScore === null || r.match.awayScore === null) continue; const p = calculatePredictionPoints({ home: r.match.homeScore, away: r.match.awayScore }, { home: r.prediction.predictedHomeScore, away: r.prediction.predictedAwayScore }); const x = table.get(r.user.id) ?? { name: r.user.displayName, played: 0, exact: 0, correct: 0, points: 0 }; x.played++; x.points += p; if (p === 5) x.exact++; if (p > 0) x.correct++; table.set(r.user.id, x) } res.status(200).json([...table.values()].sort((a,b) => b.points-a.points || b.exact-a.exact || b.correct-a.correct)); return }
  if (path[0] === 'me' && req.method === 'GET') { res.status(200).json(await requireUser(req)); return }
  if (path[0] === 'statistics' && req.method === 'GET') { const user = await requireUser(req); const rows = await db.select({ prediction: predictions, match: matches }).from(predictions).innerJoin(matches, eq(predictions.matchId, matches.id)).where(and(eq(predictions.userId, user.id), eq(matches.isFinished, true), eq(matches.isActive, true))).orderBy(desc(matches.matchDate)); let points = 0, exact = 0, correct = 0, wrong = 0, galaPredictedGoals = 0, galaActualGoals = 0; const latest: number[] = []; let rightStreak = 0, wrongStreak = 0, maxRight = 0, maxWrong = 0; for (const r of rows) { if (r.match.homeScore === null || r.match.awayScore === null) continue; const p = calculatePredictionPoints({ home: r.match.homeScore, away: r.match.awayScore }, { home: r.prediction.predictedHomeScore, away: r.prediction.predictedAwayScore }); points += p; latest.push(p); if (p === 5) exact++; if (p > 0) { correct++; rightStreak++; wrongStreak = 0; maxRight = Math.max(maxRight, rightStreak) } else { wrong++; wrongStreak++; rightStreak = 0; maxWrong = Math.max(maxWrong, wrongStreak) } const galaHome = r.match.homeTeamId === Number(process.env.TARGET_TEAM_ID ?? 645); galaPredictedGoals += galaHome ? r.prediction.predictedHomeScore : r.prediction.predictedAwayScore; galaActualGoals += galaHome ? r.match.homeScore : r.match.awayScore } const played = correct + wrong; res.status(200).json({ totalPoints: points, played, exactScores: exact, correctResults: correct, wrongResults: wrong, successRate: played ? Math.round(correct / played * 100) : 0, lastFivePoints: latest.slice(0, 5), longestCorrectStreak: maxRight, longestWrongStreak: maxWrong, predictedGalatasarayGoalAverage: played ? galaPredictedGoals / played : 0, actualGalatasarayGoalAverage: played ? galaActualGoals / played : 0 }); return }
  if (path[0] === 'admin' && path[1] === 'sync-fixtures' && req.method === 'POST') { await requireAdmin(req); res.status(200).json({ synced: await syncGalatasarayFixtures() }); return }
  if (path[0] === 'admin' && path[1] === 'matches' && path[2] && req.method === 'PATCH') { await requireAdmin(req); const input = body(req) as Record<string, unknown>; const values: Record<string, unknown> = { updatedAt: new Date(), manualOverride: true }; if (typeof input.matchDate === 'string' && !Number.isNaN(Date.parse(input.matchDate))) values.matchDate = new Date(input.matchDate); if (allowedScore(input.homeScore)) values.homeScore = input.homeScore; if (allowedScore(input.awayScore)) values.awayScore = input.awayScore; if (typeof input.isActive === 'boolean') values.isActive = input.isActive; if (['scheduled','live','finished','postponed','cancelled'].includes(String(input.status))) { values.status = input.status; values.isFinished = input.status === 'finished' } const [updated] = await db.update(matches).set(values).where(eq(matches.id, path[2])).returning(); if (!updated) throw new ApiError(404, 'Maç bulunamadı.'); res.status(200).json(updated); return }
  throw new ApiError(404, 'Endpoint bulunamadı.');
 } catch (error) { replyError(res, error) } }
